/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_bob_newndktest_JNI */

#ifndef _Included_sun_bob_newndktest_JNI
#define _Included_sun_bob_newndktest_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_bob_newndktest_JNI
 * Method:    sayMyName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_sun_bob_newndktest_JNI_sayMyName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
